language: python
python:
  - 3.6

before_install:
  - pip install -r requirements.txt
  - cpanm --notest Devel::Cover::Report::Coveralls
  
script:
  - python -m unittest -v test_ireporter.py

after_success:
  - cover -test -report coveralls